# Azure DevOps Pipeline for PACE Insurance Server
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '20.x'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildJob
    displayName: 'Build Server'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'

    - script: |
        cd server
        npm ci
      displayName: 'Install dependencies'

    - script: |
        cd server
        npm run build
      displayName: 'Build TypeScript'

    - script: |
        cd server
        npm test
      displayName: 'Run tests'
      continueOnError: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'server/dist'
        artifactName: 'server-dist'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy to Azure'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Your-Azure-Service-Connection'
              appName: 'pace-insurance-server'
              package: '$(Pipeline.Workspace)/server-dist'
              appSettings: |
                -NODE_ENV production
                -PORT 8080
